### ISSUE TITLE
Quick repro on OpenAI-ada regressions

### ISSUE THREAD

**Issue by lintool** [castorini/ura-projects#19]
I need a quick independent check that these work:

https://github.com/castorini/anserini/blob/master/docs/regressions/regressions-msmarco-passage-openai-ada2.md
https://github.com/castorini/anserini/blob/master/docs/regressions/regressions-dl19-passage-openai-ada2.md
https://github.com/castorini/anserini/blob/master/docs/regressions/regressions-dl20-passage-openai-ada2.md

It's just a matter of copy/pasting a bunch of commands and verifying the output - and then sending a PR updating the repro log.
These should run fine on student Linux environment.

Also read our paper: https://arxiv.org/abs/2308.14963

**Comment by techandy42** [comment]
I will look into this.

**Comment by Melissa1412** [comment]
Will take a look at this.

**Comment by lintool** [comment]
No longer needed.
