### ISSUE TITLE
Extend onboarding docs to learned sparse representations

### ISSUE THREAD

**Issue by lintool** [castorini/ura-projects#22]
Currently, our onboarding docs do not covered learned sparse representations:
https://github.com/castorini/onboarding?tab=readme-ov-file#-foundations-of-retrieval

Let's extend to, say, SPLADE++ ED?

**Comment by Melissa1412** [comment]
On it

**Comment by Melissa1412** [comment]
https://github.com/castorini/onboarding
https://github.com/castorini/anserini/pull/2351
https://github.com/castorini/pyserini/pull/1779
