### ISSUE TITLE
Search frontend directly in Anserini

### ISSUE THREAD

**Issue by lintool** [castorini/ura-projects#28]
Maybe something like https://vaadin.com/ ?

**Comment by 16BitNarwhal** [comment]
I'm working on this

**Comment by chloeqxq** [comment]
I'm working on this

**Comment by lintool** [comment]
Related to #6 - further down the road, a goal would be to align the look-and-feel and demos in Pyserini/Anserini. That is, they'll have the same HTML rendering/styling... but one would be in Java, other in Python.

**Comment by lintool** [comment]
@16BitNarwhal @chloeqxq now that you've experimented with Vaadin sufficiently to form some opinions about it... let's take a step back and evaluate our design choices...

Some more digging around I found:

+ Critique: https://www.reddit.com/r/java/comments/ykgcnq/why_is_vaadins_adoption_small/
+ Alternative = react.js with Java backend: https://www.linkedin.com/posts/rachid-goujdad_developing-a-react-app-with-a-java-backend-activity-7120033542654279680-Tg_Q/
+ https://spring.io/guides/tutorials/react-and-spring-data-rest

**Comment by lintool** [comment]
+ Java EE vs. Spring: https://anywhere.epam.com/en/blog/spring-vs-java-ee
+ old but maybe still useful? https://github.com/amagge/lucene-services

**Comment by lintool** [comment]
From https://vaadin.com/docs/latest/tutorial/overview - Web Applications with Spring Boot & Vaadin
Seems like with the suggested combination, Vaadin can be swapped for, say, react.

**Comment by 16BitNarwhal** [comment]
Will use Spring Boot backend and React frontend to start a site that allows searching through a prebuilt 
index using SimpleSearcher.
The run command will look something like
`java -cp anserini-0.24.2-fatjar.jar io.anserini.demo.Miracl`

Aiming to complete by March 30th

**Comment by lintool** [comment]
This has been merged in https://github.com/castorini/anserini/pull/2425 - thanks @16BitNarwhal @chloeqxq !

Much more to do, but closing this specific issue.
