### ISSUE TITLE
build an retriever arena on huggingface

### ISSUE THREAD

**Issue by MXueguang** [castorini/ura-projects#42]
using pyserini to host a bunch of corpus, use open souced embedding model as reranker to show user the difference of retrieval results.
https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard

motivation:
with the improvement of opensourced/commercial embedding model retriever user want to know whats the difference between all the retrievers before they encode for entire corpus and pay api. and there will be more and more opensourced embedding models come out..

**Comment by RohanNankani** [comment]
I am working on this.

**Comment by MXueguang** [comment]
https://x.com/muennighoff/status/1818321512639987739?s=46

this seems to be a good one.
